ITSM/Models/Project.cs
#pragma warning disable CS8618

using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace ITSM.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [ValidateNever]
        public IEnumerable<WorkItem> WorkItems { get; set; }
        [ValidateNever]
        public IEnumerable<Comment> Comments { get; set; }
    }
}

ITSM/Controllers/ProjectController.cs
using ITSM.Data;
using ITSM.Models;
using ITSM.Services;
using ITSM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITSM.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;

        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var truncatedProjects = _projectService.GetAll();

            return View(truncatedProjects);
        }

        [HttpPost]
        public IActionResult Create(ProjectDetailsViewModel projectDetailsVM)
        {
            if (!ModelState.IsValid)
                return View(nameof(Details), projectDetailsVM);

            var result = _projectService.Create(projectDetailsVM);

            if (result) TempData["success"] = "Project has been created successfully.";
            else TempData["error"] = "Something went wrong while creating a project.";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var projectDetailsVM = _projectService.GetProjectDetailsVM(id);

            if (projectDetailsVM == null)
                return RedirectToAction(nameof(Index));

            return View(projectDetailsVM);
        }

        [HttpPost]
        public IActionResult Update(ProjectDetailsViewModel projectDetailsVM, int id)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Details), new { projectDetailsVM.Project.Id });

            var result = _projectService.Update(projectDetailsVM);

            if (result) TempData["success"] = "Project has been updated succesfully.";
            else TempData["error"] = "Something went wrong while updating the project.";

            return RedirectToAction(nameof(Details), new { projectDetailsVM.Project.Id });
        }

        public IActionResult Delete(int id)
        {
            var result = _projectService.Delete(id);

            if (result) TempData["success"] = "Project has been deleted succesfully.";
            else TempData["error"] = "Something went wrong while deleting the project.";

            return RedirectToAction(nameof(Index));
        }
    }
}

ITSM/Controllers/WorkItemController.cs
using ITSM.Models;
using ITSM.Services;
using ITSM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Transactions;

namespace ITSM.Controllers
{
    [Authorize]
    public class WorkItemController : Controller
    {
        private readonly IWorkItemService _workItemService;

        public WorkItemController(IWorkItemService workItemService)
        {
            _workItemService = workItemService;
        }

        public IActionResult Index()
        {
            var workItems = _workItemService.GetAll();

            return View(workItems);
        }

        [HttpGet]
        public IActionResult Details(int id, string? discriminator)
        {
            var workItemVM = _workItemService.GetViewModel(id, discriminator);

            if (workItemVM == null)
            {
                TempData["error"] = "Bad request.";
                return RedirectToAction(nameof(Index));
            }

            return View(workItemVM);
        }

        [HttpPost]
        public IActionResult Create(WorkItemDetailsViewModel workItemVM)
        {
            if (!ModelState.IsValid)
                return View(nameof(Details), workItemVM);

            var result = _workItemService.Create(workItemVM);

            if (result) TempData["success"] = "Task has been created successfully.";
            else TempData["error"] = "Something went wrong while creating your task.";

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Update(WorkItemDetailsViewModel workItemVM)
        {
            if (!ModelState.IsValid)
                return View(workItemVM);

            var result = _workItemService.Update(workItemVM);

            if (result) TempData["success"] = "Task has been updated successfully.";
            else TempData["error"] = "Something went wrong while updating your task.";

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var result = _workItemService.Delete(id);

            if (result) TempData["success"] = "Task has been deleted successfully.";
            else TempData["error"] = "Something went wrong while deleting your task.";

            return RedirectToAction(nameof(Index));
        }
    }
}

ITSM/Views/Project/Details.cshtml
@using Microsoft.AspNetCore.Identity;
@using ITSM.ViewModels;
@model ProjectDetailsViewModel

@inject UserManager<IdentityUser> UserManager

@{
    var user = UserManager.GetUserAsync(User).Result as User;
}

<form class="mb-5" method="post" asp-action="@(Model.Project.Id == 0 ? "Create" : "Update")">
    <div class="row d-flex justify-content-center">

        <div class="col-md-12 col-xl-6 px-3">
            <div class="form-floating mb-5 mx-auto">
                <input hidden asp-for="Project.Id" />
                <textarea hidden id="description" asp-for="Project.Description"></textarea>
                <input id="projectName" asp-for="Project.Name" class="form-control" placeholder="Project name" />
                <label asp-for="Project.Name">Project name</label>
                <span asp-validation-for="Project.Name" class="text-danger"></span>
            </div>

            <div id="standalone-container">
                <div id="toolbar-container" class="d-none">
                    <span class="ql-formats">
                        <select class="ql-font"></select>
                        <select class="ql-size"></select>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-bold"></button>
                        <button class="ql-italic"></button>
                        <button class="ql-underline"></button>
                        <button class="ql-strike"></button>
                    </span>
                    <span class="ql-formats">
                        <select class="ql-color"></select>
                        <select class="ql-background"></select>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-script" value="sub"></button>
                        <button class="ql-script" value="super"></button>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-header" value="1"></button>
                        <button class="ql-header" value="2"></button>
                        <button class="ql-blockquote"></button>
                        <button class="ql-code-block"></button>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-list" value="ordered"></button>
                        <button class="ql-list" value="bullet"></button>
                        <button class="ql-indent" value="-1"></button>
                        <button class="ql-indent" value="+1"></button>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-direction" value="rtl"></button>
                        <select class="ql-align"></select>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-link"></button>
                        <button class="ql-image"></button>
                        <button class="ql-video"></button>
                        <button class="ql-formula"></button>
                    </span>
                    <span class="ql-formats">
                        <button class="ql-clean"></button>
                    </span>
                </div>
                <div id="editor-container" class="border shadow"></div>
            </div>

            <span asp-validation-for="Project.Description" class="text-danger"></span>

            <button id="saveChanges" type="submit" class="btn btn-primary rounded-0 px-3 float-end @(Model.Project.Id == 0 ? "" : "d-none")">Save changes</button>
        </div>
    </div>
</form>

<div class="row mb-5 d-flex justify-content-center">
    <div class="col-md-12 col-xl-6 px-3">
        @if (Model.Project.WorkItems != null && Model.Project.WorkItems.Any())
        {
            <h4>Assigned to this project.</h4>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Priority</th>
                        <th scope="col">State</th>
                        <th scope="col">User</th>
                        <th scope="col">Type</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Project.WorkItems)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td><a asp-controller="WorkItem" asp-action="Details" asp-route-id="@item.Id">@item.Title</a></td>
                            <td>@item.Priority</td>
                            <td>@(item.State?.Name ?? "Unassigned")</td>
                            <td>@(item.User == null ? "Unassigned" : $"{item.User.Forename} {item.User.Surname}")</td>
                            <td>@item.Discriminator</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<div class="row my-5 d-flex justify-content-center">
    <div class="col-md-12 mb-5 col-xl-6 px-3">
        @if (Model.UnassignedWorkItems != null && Model.UnassignedWorkItems.Any())
        {
            <h4>Not assigned to any project.</h4>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Priority</th>
                        <th scope="col">State</th>
                        <th scope="col">User</th>
                        <th scope="col">Type</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.UnassignedWorkItems)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td><a asp-controller="WorkItem" asp-action="Details" asp-route-id="@item.Id">@item.Title</a></td>
                            <td>@item.Priority</td>
                            <td>@(item.State?.Name ?? "Unassigned")</td>
                            <td>@(item.User == null ? "Unassigned" : $"{item.User.Forename} {item.User.Surname}")</td>
                            <td>@item.Discriminator</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        const commentTextArea = document.getElementById("commentContent");
        const commentHeightLimit = 320;

        if (commentTextArea) {
            commentTextArea.style.height = "";
            commentTextArea.style.height = Math.min(commentTextArea.scrollHeight + 2, commentHeightLimit) + "px";

            commentTextArea.oninput = function () {
                commentTextArea.style.height = "";
                commentTextArea.style.height = Math.min(commentTextArea.scrollHeight + 2, commentHeightLimit) + "px";
            };
        }

        const comments = document.querySelectorAll('.comment');

        for (let comment of comments) {
            comment.style.height = "";
            comment.style.height = comment.scrollHeight + 2 + "px";
        }
    </script>

    <script>

        const createMode = @((Model.Project.Id == 0).ToString().ToLower());

        window.addEventListener('DOMContentLoaded', function () {

            const descriptionInput = document.getElementById('description');

            if (descriptionInput.innerText != null && descriptionInput.innerText != '') {
                var delta = JSON.parse(descriptionInput.innerHTML);
                quill.setContents(delta);
            }

            quill.on('text-change', function () {
                descriptionInput.innerHTML = JSON.stringify(quill.getContents());
                unsavedChanges = true;
                if (!createMode) {
                    document.querySelector('#saveChanges').classList.remove('d-none');
                }
            });

            if (!createMode) {
                quill.disable();
            }
        });

        window.onload = function () {
            window.addEventListener("beforeunload", function (e) {
                if (unsavedChanges) {
                    e.preventDefault();
                    e.returnValue = '';
                }
            });
        };

        document.querySelector('#saveChanges').addEventListener('click', function () {
            unsavedChanges = false;
        })

        var quill = new Quill('#editor-container', {
            modules: {
                formula: true,
                syntax: true,
                toolbar: '#toolbar-container'
            },
            placeholder: 'Put your description here...',
            theme: 'snow'
        });

        var isEditorDisabled = true;

        const editorContainer = document.getElementById('standalone-container');

        editorContainer.addEventListener('click', function (range) {
            if (isEditorDisabled) {
                document.querySelector('#toolbar-container').classList.remove('d-none');
                document.querySelector('#editor-container').classList.remove('border-0');

                quill.enable();
                quill.focus();
                isEditorDisabled = false;
            }
        });

        document.onkeydown = function (e) {
            e = e || window.event;
            if (e.keyCode == 27 && !isEditorDisabled) {
                document.querySelector('#toolbar-container').classList.add('d-none');
                document.querySelector('#editor-container').classList.add('border-0');

                quill.blur();
                quill.disable();
                isEditorDisabled = true;
            }
        };

        var descriptionInput = document.getElementById('description');

        quill.on('text-change', function () {
            descriptionInput.innerHTML = JSON.stringify(quill.getContents());
        });


        var unsavedChanges = false;
        const nameInput = document.getElementById('projectName');

        nameInput.addEventListener('input', function () {
            document.querySelector('#saveChanges').classList.remove('d-none');
            unsavedChanges = true;
        });

    </script>
}

ITSM/Views/Project/Index.cshtml
@model IEnumerable<Project>

@using Microsoft.AspNetCore.Identity;

<nav id="toolbar" class="navbar navbar-expand-lg navbar-light border-bottom border-dark">
    <div class="container-fluid">
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#toolbar" aria-controls="toolbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start">
            <ul class="navbar-nav flex-grow-1">
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item nav-item-hover">
                        <a class="nav-link" asp-action="Details">
                            <i class="bi bi-plus-lg"></i>
                            Add new
                        </a>
                    </li>
                }
                <li class="nav-item mx-2">
                    <input type="search" id="searchQuery" class="form-control" placeholder="Search..." aria-label="Search" />
                </li>
            </ul>
        </div>
    </div>
</nav>

@if (!Model.Any())
{
    <h3>There are no projects to show.</h3>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th width="5%" scope="col">Id</th>
                <th scope="col">Name</th>
                <th width="5%" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>

                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <a asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                        }
                        else
                        {
                            @item.Name
                        }
                    </td>
                    <td>
                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <a id="contextMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots"></i>
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="contextMenu">
                                <li>
                                    <!-- MODAL TRIGGER -->
                                    <a href="#" class="dropdown-item d-flex justify-content-md-between" data-bs-toggle="modal" data-bs-target="#deleteModal@(item.Id)">Delete</a>
                                </li>
                            </ul>

                            <!-- MODAL START -->
                            <div class="modal fade" id="deleteModal@(item.Id)" tabindex="-1" aria-labelledby="deleteModal@(item.Id)Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">@item.Name</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this project?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a class="btn btn-danger" asp-controller="Project" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- MODAL END -->
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}