ITSM/Controllers/JobPositionController.cs
using ITSM.Models;
using ITSM.Services;
using ITSM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITSM.Controllers
{
    [Authorize]
    public class JobPositionController : Controller
    {
        private readonly IJobPositionService _jobPositionService;

        public JobPositionController(IJobPositionService jobPositionService)
        {
            _jobPositionService = jobPositionService;
        }

        public IActionResult Index()
        {
            var jobPositions = _jobPositionService.GetAll();

            var jobPositionVM = new PositionViewModel()
            {
                Position = new JobPosition(),
                JobPositions = jobPositions
            };

            return View(jobPositionVM);
        }

        [HttpPost]
        public IActionResult Index(PositionViewModel jobPositionVM)
        {
            var result = _jobPositionService.AddJobPosition(jobPositionVM.Position);

            if(result) TempData["success"] = $"{jobPositionVM.Position.Position} has been added!";
            else TempData["error"] = "Something went wrong, please try again.";

            return RedirectToAction(nameof(Index));
        }
    }
}

ITSM/Controllers/ToolsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITSM.Controllers
{
    public class ToolsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ITSM/Views/Tools/Index.cshtml
<div class="row">
    <a asp-controller="JobPosition" asp-action="Index" class="card text-decoration-none text-white bg-dark mx-3" style="max-width: 18rem;">
        <div class="card-header"><i class="bi bi-gear-fill"></i></div>
        <div class="card-body">
            <h5 class="card-title">Job positions</h5>
            <p class="card-text">Add job positions to fit company requirements.</p>
        </div>
    </a>

    <a asp-area="Identity" asp-page="/Account/RegisterEmployee" class="card text-decoration-none text-white bg-dark mx-3" style="max-width: 18rem;">
        <div class="card-header"><i class="bi bi-person-badge-fill"></i></div>
        <div class="card-body">
            <h5 class="card-title">Register employee</h5>
            <p class="card-text">Register a new employee account with required accesses.</p>
        </div>
    </a>
</div>